### ISSUE TITLE
cake-watch does not pickup changes made in Visual Studio

### ISSUE THREAD

**Issue by rbutcher** [wk-j/cake-watch#2]
## Description
I believe this is due to the way that Visual Studio writes changes to the file as outlined by this SO question.
[Why doesn't FileSystemWatcher detect changes from Visual Studio?](http://stackoverflow.com/questions/680698/why-doesnt-filesystemwatcher-detect-changes-from-visual-studio)

## Environment
Windows 10 x64
Visual Studio 2015 Update 3
Cake v0.15.2
Cake.Watch from nuget v0.1.4

## Steps to Recreate
1.) Start cake watch by calling custom Task() in .cake script
2.) Change any file that should be watched from Visual Studio
3.) Observe as cake-watch does not run the registered delegate.

## build.cake
```
#addin nuget:?package=Cake.Watch

var target = Argument("target", "Build");
var configuration = Argument("configuration", "Release");

Task("Build")
    .Does(() => {              
        MSBuild(
            solution : "./SystemAssessmentTool.sln",
            settings : new MSBuildSettings {
                ToolVersion = MSBuildToolVersion.VS2015,
                Configuration = configuration,
                PlatformTarget = PlatformTarget.x86,
                MaxCpuCount = 0,
                Verbosity = Verbosity.Quiet
        });
    });

Task("Clean")
    .Does(() => {
        CleanDirectories("./**/build");
    });

Task("Test")
    .IsDependentOn("Build")
    .Does(() => {
        var runnerGlob = "./**/build/" + configuration + "/bin/*.UnitTests.exe";
        var runners = GetFiles(runnerGlob);
        foreach (var runner in runners)
        {
            Information(runner.ToString());
            StartAndReturnProcess(runner).WaitForExit();
        }
    });

Task("Watch")
    .Does(() =>
    {
        Func<string, bool> isTargetFileType = s => s.EndsWith(".cpp") || s.EndsWith(".h");
        
        Watch("*", c => {
            if(!isTargetFileType(c)) return;
            try { RunTarget("Test"); }
            catch { Warning("Build Failed!"); }
        });

    });

RunTarget(target);
```

**Comment by wk-j** [comment]
Thanks for reports 
I don't have Windows machine to test now, I will check this on Monday.

**Comment by rbutcher** [comment]
Opened PR with changes https://github.com/wk-j/cake-watch/pull/3 

Its a bit of a heavy handed change but it does the job. I also think it will be more reliable to cut down on the spammy nature of saving in Visual Studio.

**Comment by wk-j** [comment]
Thanks
I just publish this fixed with Cake.Watch 0.1.5
